### ISSUE TITLE
Error with new TER version

### ISSUE THREAD

**Issue by DavidBruchmann** [lochmueller/cache_check#6]
Fatal error: Class 'HDNET\Autoloader\Loader' not found in D:_**WWW_**_typo3_PROJECTS\syriansabroad.de\typo3conf\ext\cache_check\ext_localconf.php on line 20

... is shown directly after installation.
TYPO3 Version 6.2.12

**Comment by DavidBruchmann** [comment]
Missing dependency to extension autoloader?

**Comment by DavidBruchmann** [comment]
yes, installing extension autoloader first solves the issue

**Comment by lochmueller** [comment]
Hey David,

do you install the extension via the EM or via Download/typo3.org and upload to your TYPO3? There are valid dependencies (https://github.com/lochmueller/cache_check/blob/master/ext_emconf.php) but if you download a extension on typo3.org the dependencies are empty. This is a bug (feature?!) of the TER?

Regards,
Tim

**Comment by DavidBruchmann** [comment]
Hi Tim,

as the Extension was not found in TER by the extension-manager I downloaded it from TER manually and uploaded it then.
About strange features or bugs of the TER I can't say anything as I never verified misbehavior there.

Thanks,
David

**Comment by lochmueller** [comment]
Hey David,

I test it with 2 other extensions. If you download the extension via the TER Website and install it in the backend, there are no dependencies in the ext_emconf.php anymore. Sorry... but it seems to be a TER problem.

Regards,
Tim

**Comment by DavidBruchmann** [comment]
Hey Tim,

ok, thanks for the checks.

Best Regards,
David
